package com.exam.madding;
// Generated May 29, 2018 12:17:58 AM by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Mschedule generated by hbm2java
 */
public class Mschedule implements java.io.Serializable {

    private String smdate;
    private java.sql.Date mdate;
    private String sdate;
    private String mname;
    private Integer dsprice;
    private Integer psprice;
    private Integer gsprice;
    private Integer ssprice;

    public Mschedule() {
    }

    public Mschedule(java.sql.Date mdate, String mname, Integer dsprice, Integer psprice, Integer gsprice, Integer ssprice) {
     //   this.smdate = smdate;
        this.mdate = mdate;
        this.mname = mname;
        this.dsprice = dsprice;
        this.psprice = psprice;
        this.gsprice = gsprice;
        this.ssprice = ssprice;
    }

    public Mschedule(java.sql.Date mdate, String mname) {
        this.mdate = mdate;
        this.mname = mname;
    }

    public String getMname() {
        return mname;
    }

    public void setMname(String mname) {
        this.mname = mname;
    }

    public String getSmdate() {
        return smdate;
    }

    public void setSmdate(String smdate) {
        this.smdate = smdate;
    }

    public java.sql.Date getMdate() {
        return mdate;
    }

    public void setMdate(java.sql.Date mdate) {
        this.mdate = mdate;
    }

    public String getSdate() {
        return sdate;
    }

    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    public Integer getDsprice() {
        return dsprice;
    }

    public void setDsprice(Integer dsprice) {
        this.dsprice = dsprice;
    }

    public Integer getPsprice() {
        return psprice;
    }

    public void setPsprice(Integer psprice) {
        this.psprice = psprice;
    }

    public Integer getGsprice() {
        return gsprice;
    }

    public void setGsprice(Integer gsprice) {
        this.gsprice = gsprice;
    }

    public Integer getSsprice() {
        return ssprice;
    }

    public void setSsprice(Integer ssprice) {
        this.ssprice = ssprice;
    }
    
    

}